### PR TITLE
Make this thing actually, you know, work.

### LINKED ISSUE #6: Cannot import into an Ember app
I tried to import `Field`, and there were no type errors:

```TypeScript
import { Field } from '@olo/principled-forms';
```

However, when I actually try to do anything with it, e.g. `console.log(Field.optional)`, I get the following error:

> Error: Could not find module `@olo/principled-forms` imported from `principled-forms-repro/components/issue-repro`

[Repro repository](https://github.com/tansongyang/principled-forms-repro/tree/cannot-import)

I noticed the following message in Ember CLI and am wondering if it could be related:

> The package `@olo/principled-forms` is not a properly formatted package, we have used a fallback lookup to resolve it at `C:\GitHub\principled-forms-repro\node_modules\@olo\principled-forms`. This is generally caused by an addon not having a `main` entry point (or `index.js`).

### PR DESCRIPTION
**Pull request by chriskrycho**
Fixes #6.

### CODE REVIEW

**Comment by tansongyang** [comment]
Does this mean that this library becomes targeted only at Ember projects? Also, I've tried this locally and it doesn't appear to solve the problem.

**Comment by chriskrycho** [comment]
No, it’ll work in general; “main” is a normal npm package key, not an Ember key. I’m doing some further testing and validation; there are annoyances around the installation of a branch for a scoped repo.

**Comment by tansongyang** [comment]
Right, what I mean is that, since we're setting "main" to be "ember-addon.js", won't that clash with anything else that might refer to "main"?

To elaborate on what I did: I made this same code change in the `package.json` in my `node_modules` folder. That didn't seem to fix the problem.

**Comment by chriskrycho** [comment]
It shouldn’t; this isn’t a file meant to be executed as a Node module other than as an Ember addon. Any other consumer (e.g. Webpack etc.) will just target the `build` directory and be fine.

In any case, I should have thrown a WIP note on this; I'm still experimenting with what's required locally.

**Comment by chriskrycho** [comment]
Fixed it. Pushing so we can test the branch.

**Comment by tansongyang** [comment]
Yes, I can confirm that this fixes this specific issue. Further exploration led me to discover some other bugs, but I will report those separately.

**Comment by chriskrycho** [comment]
Needs https://github.com/chriskrycho/true-myth/pull/14 to finish fixing _everything_; once that's published I'll push an update that includes that here.

**Comment by chriskrycho** [comment]
Further update: we actually need https://github.com/chriskrycho/true-myth/pull/15 to land to fix the remaining type errors. I'm going to cut that as a 2.0.0-beta.1 release tomorrow morning first thing.

**Pull request merged**
