### PR TITLE
Update ember version to 3.11

### PR DESCRIPTION
**Pull request by dollhause**
I tried to update all of the dependencies to get a clean install, build, and test for the `@olo/ember-principled-forms` package, but couldn't prevent getting warnings for `caniuse-lite` being out of date and the `class-properties` module being defined mysteriously by some other package. I tried walking the dep map and saw a lot of duplication spinning out of `ember-cli-addon-docs`, but it was really hard to sort out what we coming from where.

I also get the jQuery warnings, but didn't dig into those at all.

### CODE REVIEW

**Review by billpull — DISMISSED** [review]

**Review by dustinsoftware — COMMENTED** [review]
This looks good as long as it does not _require_ the use of Ember 3.11, since Ember 3.8 is current LTS

**Review by JonRossway — DISMISSED** [review]

**Comment by JonRossway** [comment]
@dollhause has this been tested being consumed by Expo? Curious to see if those errors cause problems end-to-end

**Comment by dollhause** [comment]
> This looks good as long as it does not _require_ the use of Ember 3.11, since Ember 3.8 is current LTS

It would require the use of Ember >=3.10, that's why my instinct was to major it. I had asked Bill this question over slack when I opened the PR. There's some bad dependency design happening somewhere. I'm not familiar with how ember is resolving its deps, but, even though `ember-decorators` should be a separate module in the tree, as soon as I update ember to include the native syntax, any modules currently using `import { computed } from "@ember-decorators/object"` will throw saying the method is being used incorrectly. It's very weird. Maybe an update to the babelification that comes with `ember-cli`?

**Comment by dollhause** [comment]
> @dollhause has this been tested being consumed by Expo? Curious to see if those errors cause problems end-to-end

I have tested it along with updating the app to ember >= 3.10. It will break the app if it isn't updated at the same time, since the native decorators aren't available without the update or by adding the decorators polyfill.

**Comment by dustinsoftware** [comment]
Yeah the upgrade path for addons using ember-decorators was a bit painful for mobile-web, but we are over that hump now that we are on 3.10. I'd be fine requiring it as long as all consumers of this addon are ready to upgrade, or we will need to support a legacy branch of principled-forms in order to patch downstream dependencies

**Comment by billpull** [comment]
I believe Expo is the only internal usage. If there are any non-ololabs consumers I think updating the readme to say if ember < 3.10 pin to version 0.2.5 would be sufficient.

**Comment by chriskrycho** [comment]
For whatever it's worth, I never publicized this outside Olo and npm itself does not report any public users of the package, and those 14 downloads a week look like they should all be you folks—I'd recommend a 0.3.0 version but I think the guidance above is probably fine as well in that decorator consumption *should* be non-breaking, modulo conflicting versions of the decorator helpers.

Semi-related: you're likely to see some minor annoyances/CLI output warnings from ember-cli-typescript until we cut our 3.0.0 release (probably mid to late next week).

(I may ping some of you good folks to collaborate on pushing this forward sometime in early 2020; or I'll watch with interest as you develop it in the interval. I still have a bunch of ideas here but am very much underwater with other TS-related concerns.)

**Review by billpull — APPROVED** [review]

**Pull request merged**
